
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      runs: {
        Row: {
          id: string
          userId: string
          date: string
          distance: number
          duration: number
          notes?: string | null
          status: 'Completed' | 'In Progress' | 'Cancelled'
          created_at?: string
        }
        Insert: {
          id?: string
          userId: string
          date: string
          distance: number
          duration: number
          notes?: string | null
          status: 'Completed' | 'In Progress' | 'Cancelled'
          created_at?: string
        }
        Update: {
          id?: string
          userId?: string
          date?: string
          distance?: number
          duration?: number
          notes?: string | null
          status?: 'Completed' | 'In Progress' | 'Cancelled'
          created_at?: string
        }
      }
      goals: {
        Row: {
          id: string
          userId: string
          targetDate: string
          targetDistance: number
          targetPace: number
          status: 'Active' | 'Completed' | 'Failed' | 'Cancelled'
          autoGenerated: boolean
          created_at: string
        }
        Insert: {
          id?: string
          userId: string
          targetDate: string
          targetDistance: number
          targetPace: number
          status: 'Active' | 'Completed' | 'Failed' | 'Cancelled'
          autoGenerated: boolean
          created_at?: string
        }
        Update: {
          id?: string
          userId?: string
          targetDate?: string
          targetDistance?: number
          targetPace?: number
          status?: 'Active' | 'Completed' | 'Failed' | 'Cancelled'
          autoGenerated?: boolean
          created_at?: string
        }
      }
    }
  }
}
