
export interface GoalData {
  id: string;
  userId: string;
  targetDate: Date;
  targetDistance: number; // in kilometers
  targetPace: number; // in seconds per kilometer
  status: 'Active' | 'Completed' | 'Failed' | 'Cancelled';
  autoGenerated: boolean;
  createdAt: Date;
}
